apiVersion: log.jdcloud.com/v1
kind: DiggerLogConfigDefinition
metadata:
  name: diggers.log.jdcloud.com
spec:
  group: log.jdcloud.com
  names:
    categories:
    - logtrait
    - all
    kind: DiggerLogConfigDefinition
    plural: diggerlogconfigdefinitions
    shortNames:
    - digger
    singular: diggerlogconfigdefinition
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: 各个产品线日志初始化采集配置
        properties:
          spec:
            properties:
              cluster-size:
                default: 3
                maximum: 7.0
                type: integer
              resource-limits:
                properties:
                  CPU:
                    minimum: 1.0
                    type: integer
                  Disk:
                    type: string
                  RAM:
                    type: string
                type: object
              mysql-version:
                type: number
            required:
            - autoscaling
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
